apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: duynamic-select-template
  title: Example for template that dynamically fetches the options
  description: An example of a template that dynamically fetches countries and lists them as the options
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in information
      required:
        - country
      properties:
        country:
          title: Country
          type: string
          description: country
          ui:field: DynamicSelect
          ui:autofocus: true
          ui:options:
            url: https://countriesnow.space/api/v0.1/countries
            arrayKey: data
            key: country

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: debug
      name: Debug
      action: debug:log
      input:
        message: ${{ parameters.country }}
